name: flutter_prod
description: trying production level architecture with very good cli flutter bloc state management.Basically it's one of my working template for flutter application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.6.3
  intl: ^0.19.0
  shared_preferences: ^2.4.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
